export enum ResponseCodes {
  USER_NEW = 'USER_NEW',
  USER_LOGIN = 'USER_LOGIN',
  USER_EMPTY = 'USER_EMPTY',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_EXISTS = 'USER_NOT_EXISTS',
  USER_INVALID_CREDENTIALS = 'USER_INVALID_CREDENTIALS',
}
